services:
  web:
    container_name: "smart-kassa-web"
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    command: >
      sh -c "python3 src/manage.py migrate --noinput
      && python3 src/manage.py runserver 0.0.0.0:8000"
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: mysql:8
    container_name: "smart-kassa-db"
    restart: always
    env_file:
      - .env
    volumes:
      - smart_kassa_db:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  smart_kassa_db:
