services:
  web:
    container_name: "smart-kassa-web"
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    command: >
      sh -c "python3 src/manage.py migrate --noinput
      && python3 src/manage.py runserver 0.0.0.0:8000"
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: mysql:8
    container_name: "smart-kassa-db"
    restart: always
    env_file:
      - .env
    volumes:
      - smart_kassa_db:/var/lib/mysql
    ports:
      - "3306:3306"
  redis:
    image: redis:latest
    container_name: "smart-kassa-redis"
    restart: always
    ports:
      - "6379:6379"
  celery:
    container_name: "smart-kassa-celery"
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    command: >
      sh -c "cd src && celery -A config worker --loglevel=info"
    env_file:
      - .env
    depends_on:
      - redis
      - db
      - web

  celery-beat:
    container_name: "smart-kassa-celery-beat"
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    command: >
      sh -c "cd src && celery -A config beat --loglevel=info --scheduler django_celery_beat.schedulers.DatabaseScheduler"
    env_file:
      - .env
    depends_on:
      - redis
      - db
      - web
      - celery
volumes:
  smart_kassa_db:
