# Generated by Django 5.1.7 on 2025-03-19 04:37

import smartkassa.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('inn', models.CharField(max_length=14, unique=True, validators=[smartkassa.validators.validate_inn], verbose_name='СТИР')),
                ('name', models.CharField(max_length=255, verbose_name='Имя пользователя')),
                ('pinfl', models.CharField(blank=True, max_length=14, null=True, verbose_name='ПИНФЛ')),
                ('phone', models.CharField(blank=True, max_length=13, null=True, verbose_name='Телефон')),
                ('bank_name', models.CharField(max_length=255, verbose_name='Банк')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('date_birth', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('Ж', 'Female')], max_length=1, null=True, verbose_name='Пол')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
