# Generated by Django 5.1.7 on 2025-03-21 07:53

import django.db.models.deletion
import smartkassa.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartkassa', '0003_client_balance_balancetransaction'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='balancetransaction',
            options={'ordering': ['-created_at'], 'verbose_name': 'Balance transaction', 'verbose_name_plural': 'Balance transactions'},
        ),
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Client', 'verbose_name_plural': 'Clients'},
        ),
        migrations.AlterModelOptions(
            name='device',
            options={'verbose_name': 'Device', 'verbose_name_plural': 'Devices'},
        ),
        migrations.AlterField(
            model_name='balancetransaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='balancetransaction',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='smartkassa.client', verbose_name='Client'),
        ),
        migrations.AlterField(
            model_name='balancetransaction',
            name='comment',
            field=models.CharField(max_length=255, verbose_name='Comment'),
        ),
        migrations.AlterField(
            model_name='balancetransaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='balancetransaction',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='client',
            name='address',
            field=models.CharField(max_length=255, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='client',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Balance'),
        ),
        migrations.AlterField(
            model_name='client',
            name='bank_name',
            field=models.CharField(max_length=255, verbose_name='Bank'),
        ),
        migrations.AlterField(
            model_name='client',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='client',
            name='date_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Date of birth'),
        ),
        migrations.AlterField(
            model_name='client',
            name='inn',
            field=models.CharField(max_length=14, unique=True, validators=[smartkassa.validators.validate_inn], verbose_name='TIN'),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(blank=True, max_length=13, null=True, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='client',
            name='pinfl',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='PINFL'),
        ),
        migrations.AlterField(
            model_name='client',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='device',
            name='client',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='smartkassa.client', verbose_name='Client'),
        ),
        migrations.AlterField(
            model_name='device',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='device',
            name='fm_serial_number',
            field=models.CharField(blank=True, help_text='Fiscal memory', max_length=255, null=True, verbose_name='FM'),
        ),
        migrations.AlterField(
            model_name='device',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='device',
            name='kkm_serial_number',
            field=models.CharField(help_text='Cash register machine', max_length=255, unique=True, verbose_name='KKM'),
        ),
        migrations.AlterField(
            model_name='device',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='device',
            name='owner_type',
            field=models.CharField(choices=[('bank', 'Bank'), ('smartkassa', 'Smart Kassa'), ('personal', 'Personal')], max_length=10, verbose_name='Owner type'),
        ),
        migrations.AlterField(
            model_name='device',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
    ]
